server:
  image: easypi/shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=aes-256-cfb
    - PASSWORD=jD78_$Bqe4
  restart: always

client:
  image: easypi/shadowsocks-libev
  command:
    ss-local -s 1.2.3.4
             -p 8388
             -m aes-256-cfb
             -k 5ouMnqPyzseL
             -b 0.0.0.0
             -l 1080
             -t 60
             -A
             --fast-open
  ports:
    - "1080:1080"
  restart: always

client-arm:
  image: easypi/shadowsocks-libev-arm
  ports:
    - "1080:1080"
  environment:
    - SERVER_ADDR=1.2.3.4
    - METHOD=aes-256-cfb
    - PASSWORD=jD78_$Bqe4
  restart: always
